services:
  backend:
    image: fastapi-student-code
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:redhat1234@10.3.5.245:5432/postgres
      - FRONTEND_DOMAIN=http://frontend:3000
    restart: unless-stopped

  migration:
    image: fastapi-student-view-migration
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:redhat1234@10.3.5.245:5432/postgres
    command: ["./docker-entrypoint.sh", "--migrate-only"]

  frontend:
    image: nextjs-student-view
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://code.dev.akumotechnology.com/api
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend
